### ISSUE TITLE
Got crash error on beenDone from users from google play console

### ISSUE THREAD

**Issue by iballan** [jonfinerty/Once#32] opened 2017-02-24 05:57 UTC
I got this error on Crashes & ANRs in google play console from 10 users:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List ry.a(java.lang.String)' on a null object reference
	at jonathanfinerty.once.Once.initialise(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.markDone(Once.java)
	at jonathanfinerty.once.Once.initialise(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.beenDone(Once.java)
	at <OR>.markDone(Once.java)
```

I call `Once.initialise(this)` on the app class.

and this error raised in a class where I try to use `Once.beenDone`  normally on background thread.

**Comment by jonfinerty** [comment] 2017-02-25 09:29
Hi, thanks for raising this.

It looks like your stack trace there is obfuscated, do you have a non-obfuscated version? But still it looks like you're calling markDone or a similar method before initialise gets called. Are you sure your background thread always runs after initialise is finished?

I looked into having all the methods block until initialised but that complicated the code a lot, perhaps I can catch this type of error and report a more meaningful exception.

**Comment by iballan** [comment] 2017-02-25 10:01
I think it won't crash for markDone because i call beenDone first always.

For the first look, it is not possible to call any Once method before initialize because I call Once.initialise(this) on the onCreate of Application class.

by the way, I have splash screen that takes 400 milliseconds before the app goes to the main activity and start using Once.beenDone or Once.markDone. So at least between the Once.Initialise and the first usage there is 400 milliseconds.

Do you see it is a good solution to calculate at worst how long does it take to initialise Once in the first run, So i can let the other thread wait for sometime before it uses Once.beenDone?

**Comment by jonfinerty** [comment] 2017-02-25 10:11
Hmm, ok well 400ms is way more than enough to rule out beenDone occuring before initialisation. Can you get a un-obfuscated stacktrace? Is there any correlation between those 10 users, once version? android version? etc

**Comment by iballan** [comment] 2017-02-25 10:57
I have just checked it out, All of them uses Android 6.0, and all of them Samsung devices with different models. 
I use the latest Once version since i started using Once 1 month ago, and the last update was 6 months ago.

**Comment by iballan** [comment] 2017-03-29 11:19
I am still getting crash reports for this. I think i am sadly gonna get back to the old-fashioned sharedPreferences code.

**Comment by jonfinerty** [comment] 2017-04-03 20:00
Hi Again, I'm sorry to hear that. I've got some more free time recently and I can investigate this further, but a deobfuscated stacktrace, ideally with line numbers would help a lot.

**Comment by furyan87** [comment] 2017-09-20 11:20
I encountered the same problem, all with Android 6 but with multiple devices not only samsung.
I also initialize Once in the onCreate method of my application class. 
The exception happens because the tagLastSeenMap is null, which implies that the initialization wasn't called which doesn't really makes sense.

The stacktrace:

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2493)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2576)
  at android.app.ActivityThread.access$1000 (ActivityThread.java:155)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1421)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5539)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: 
  at jonathanfinerty.once.Once.beenDone (Once.java:166)
  at jonathanfinerty.once.Once.beenDone (Once.java:151)
  at de.aok.bv.kopra.schwanger.LandingActivity.onCreate (LandingActivity.java:22)
  at android.app.Activity.performCreate (Activity.java:6289)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1118)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2446)

**Comment by mradzinski** [comment] 2017-11-27 10:46
I think it all comes to `AsyncSharedPreferenceLoader`. tagLastSeenMap is of type `PersistedMap` and it makes use of `AsyncSharedPreferenceLoader` upon construction. 

I think that if you use Once way too soon during your initialization chain then there's a small chance tagLastSeenMap will still be `null`. It's a racing condition. My two cents is to make `AsyncSharedPreferenceLoader` synchronous. I don't think it'll block the app that much, and if Once is initialized during `onCreate` on the Application class then it'll just add a few milliseconds the most and will be totally transparent to the user.

**Comment by niknetniko** [comment] 2019-02-05 23:50
Has there been progress on this issue?

I think I have encountered the same issue. Stack trace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Map android.content.SharedPreferences.getAll()' on a null object reference
       at jonathanfinerty.once.PersistedMap.waitForLoad(SourceFile:32)
       at jonathanfinerty.once.Once.jonathanfinerty.once.PersistedMap.get(SourceFile:2059)
       at be.ugent.zeus.hydra.minerva.common.sync.MinervaAdapter.onPerformCheckedSync(SourceFile:92)
       at be.ugent.zeus.hydra.common.sync.AbstractAdapter.onPerformSync(SourceFile:62)
       at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:334)
 ```

The last line of code in our own code is:
```java
boolean isInitialSync = extras.getBoolean(EXTRA_FIRST_SYNC, false) || !Once.beenDone(FIRST_SYNC);
```

This error occurs during a sync with a `SyncAdapter`. If we assume there is less time between initialisation during sync (since there is no UI), this would support your theory.

**Comment by jonfinerty** [comment] 2019-08-18 19:40
Closing with version 1.3.0 - ended up following @mradzinski advice and removed the async load

**Closed by jonfinerty** 2019-08-18 19:40 UTC
